To use numpy need to import the numpy module as follows.

In [1]:
import numpy as np # naming import convention

## 2.1 Basic operations and Universal Numpy Functions

All numpy arithmetic operates element wise and are much faster than if you did them in pure python.

### Scalar-array operations


In [2]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [3]:
a + 2.5

array([ 3.5,  4.5,  5.5,  6.5])

In [6]:
b = np.array([2, 3,-1,0]) + 1

In [7]:
b

array([3, 4, 0, 1])

In [8]:
a - b

array([-2, -2,  3,  3])

Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum. For more details on numpy function visit [here](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

In [9]:
data = np.array([[32, 29, 29, 36, 30, 33, 25, 34, 32, 30],
       [28, 25, 36, 31, 29, 31, 29, 30, 35, 32],
       [29, 27, 27, 35, 32, 30, 31, 34, 27, 34]])

In [10]:
data

array([[32, 29, 29, 36, 30, 33, 25, 34, 32, 30],
       [28, 25, 36, 31, 29, 31, 29, 30, 35, 32],
       [29, 27, 27, 35, 32, 30, 31, 34, 27, 34]])

In [11]:
# Compute sum of all elements; 
np.sum(data)  

922

In [12]:
data.sum()

922

In [13]:
# Compute sum of each column; 
np.sum(data, axis=0)  

array([ 89,  81,  92, 102,  91,  94,  85,  98,  94,  96])

In [14]:
# Compute sum of each row; 
np.sum(data, axis=1) 

array([310, 306, 306])

In [17]:
#Calculate the n-th discrete difference
a= np.array([4,3,4,2,0])
np.diff(a)

array([-1,  1, -2, -2])

In [18]:
# Computing mean
data.mean()

30.733333333333334

In [19]:
data.std()

2.9881246441353295

In [20]:
# square root
np.sqrt(data)

array([[ 5.65685425,  5.38516481,  5.38516481,  6.        ,  5.47722558,
         5.74456265,  5.        ,  5.83095189,  5.65685425,  5.47722558],
       [ 5.29150262,  5.        ,  6.        ,  5.56776436,  5.38516481,
         5.56776436,  5.38516481,  5.47722558,  5.91607978,  5.65685425],
       [ 5.38516481,  5.19615242,  5.19615242,  5.91607978,  5.65685425,
         5.47722558,  5.56776436,  5.83095189,  5.19615242,  5.83095189]])

In [21]:
# max 
data.max()

36

In [22]:
data.min()

25

In [25]:
#  Product of two vectors
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])

In [26]:
np.dot(a,b)

array([[4, 1],
       [2, 2]])

In [29]:
# Or you can write
c = a.dot(b)

In [31]:
# Transpose of an array
c = np.array([[4, 1],
       [2, 2]])
c

array([[4, 1],
       [2, 2]])

In [32]:
c.T

array([[4, 2],
       [1, 2]])

### Numpy Exercise


